CREATE TABLE IF NOT EXISTS "Leads" (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(255) NOT NULL,
    course VARCHAR(255) NOT NULL,
    college VARCHAR(255) NOT NULL,
    year VARCHAR(255) NOT NULL,
    status VARCHAR(255) DEFAULT 'new',
    sheet_row_id INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS leads_email_idx ON "Leads" (email);
